development:
  cloud_name: das8ywpq1
  api_key: '777916544228959'
  api_secret: 8YbX5djyM6JdoJuDpr9DX-kXrdU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: das8ywpq1
  api_key: '777916544228959'
  api_secret: 8YbX5djyM6JdoJuDpr9DX-kXrdU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: das8ywpq1
  api_key: '777916544228959'
  api_secret: 8YbX5djyM6JdoJuDpr9DX-kXrdU
  enhance_image_tag: true
  static_image_support: false
